# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

#  List xcodes simulators and runtimes with:
#  xcrun simctl list

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  execute-unit-tests:
    name: Unit Tests
    runs-on: macos-13
    strategy:
      matrix:
        config: [debug]
        platform: [iOS, macOS]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Select Xcode 14.3
      run: sudo xcode-select -s /Applications/Xcode_14.3.app

    - name: Run tests
      run: TEMP_DIR=${{ runner.temp }} PLATFORM=${{ matrix.platform }} CONFIG=${{ matrix.config }} make github-test

    - name: Publish xcodebuild.log
      uses: actions/upload-artifact@v3
      with:
        name: xcodebuild-${{ matrix.config }}-${{ matrix.platform }}.log
        path: ${{ runner.temp }}/xcodebuild.log
