# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  execute-unit-tests:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
